name: 打印互助码&互助码自动上车

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '20 18 * * *'
  # watch:
  #   types: started
  repository_dispatch:
    types: jd_sharecode
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/sinagod/JD_ACTION.git ~/JD_ACTION
      - name: 提交互助码
        run: |
          cd ~/Actions/.github
          chmod +x jd_sharecodes.sh
          ./jd_sharecodes.sh
          git clone -b master https://gitee.com/the_king_god/lxk.script.git ~/scripts
          cd  ~/scripts
          npm install
          node jd_get_share_code.js
        env:
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PETSHARECODES: ${{ secrets.PETSHARECODES }}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES }}
          SUPERMARKET_SHARECODES: ${{ secrets.SUPERMARKET_SHARECODES }}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
          JXFACTORY_SHARECODES: ${{ secrets.JXFACTORY_SHARECODES }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
          JDZZ_INVITECODES: ${{ secrets.JDZZ_INVITECODES }}
          JDJOY_SHARECODES: ${{ secrets.JDJOY_SHARECODES }}
          JDCASH_SHARECODES: ${{ secrets.JDCASH_SHARECODES }}
